# Generated by Django 5.0.3 on 2024-04-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('advisor_id', models.CharField(db_column='Advisor ID', max_length=7, primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('mname', models.TextField()),
                ('lname', models.TextField()),
            ],
            options={
                'db_table': 'advisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(db_column='userID', max_length=7, primary_key=True, serialize=False)),
                ('area', models.TextField(db_column='Area')),
                ('city', models.TextField()),
                ('postcode', models.IntegerField()),
                ('contact_number', models.TextField()),
                ('user_type', models.TextField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackT',
            fields=[
                ('user_id', models.CharField(db_column='user_ID', max_length=7, primary_key=True, serialize=False)),
                ('feedback_number', models.CharField(max_length=5)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'feedback_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrantT',
            fields=[
                ('grant_id', models.CharField(db_column='Grant_ID', max_length=5, primary_key=True, serialize=False)),
                ('grant_amount', models.DecimalField(db_column='Grant_amount', decimal_places=0, max_digits=10)),
                ('start_date', models.DateField(db_column='Start_date')),
                ('end_date', models.DateField(db_column='End_date')),
            ],
            options={
                'db_table': 'grant_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceT',
            fields=[
                ('insurance_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=20)),
                ('effective_date', models.DateTimeField()),
                ('coverage_amount', models.IntegerField()),
                ('premium_amount', models.IntegerField()),
                ('policy_period', models.TextField()),
                ('payment_frequency', models.TextField()),
                ('payment_method', models.TextField()),
            ],
            options={
                'db_table': 'insurance_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentT',
            fields=[
                ('investment_id', models.CharField(db_column='Investment_ID', max_length=5, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('start_date', models.DateField(db_column='Start_date')),
                ('end_date', models.DateField(db_column='End_date')),
            ],
            options={
                'db_table': 'investment_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(db_column='Loan_ID', max_length=5, primary_key=True, serialize=False)),
                ('receiving_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('return_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanProvider',
            fields=[
                ('loanprovider_id', models.CharField(db_column='LoanProvider_ID', max_length=7, primary_key=True, serialize=False)),
                ('eligibility_criteria', models.TextField()),
                ('repayment_period', models.DateTimeField()),
                ('application_fee', models.TextField()),
            ],
            options={
                'db_table': 'loan_provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdvisorExpertise',
            fields=[
                ('advisor_id', models.OneToOneField(db_column='Advisor ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.advisor')),
                ('expertise', models.CharField(db_column='Expertise', max_length=30)),
            ],
            options={
                'db_table': 'advisor expertise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmerT',
            fields=[
                ('farmer', models.OneToOneField(db_column='Farmer_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.user')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('landsize', models.TextField()),
            ],
            options={
                'db_table': 'farmer_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialServiceProviderT',
            fields=[
                ('fspid', models.OneToOneField(db_column='FSPid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.user')),
                ('name', models.CharField(max_length=100)),
                ('l_field', models.TextField(db_column='L?')),
                ('ip_field', models.TextField(db_column='IP?')),
                ('g_field', models.TextField(db_column='G?')),
                ('i_field', models.TextField(db_column='I?')),
            ],
            options={
                'db_table': 'financial_service_provider_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanProviderLoanType',
            fields=[
                ('loanprovider', models.OneToOneField(db_column='LoanProvider_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.loanprovider')),
                ('loan_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'loan_provider_loan_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmerCropnameT',
            fields=[
                ('farmer', models.OneToOneField(db_column='Farmer_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.farmert')),
                ('cropname', models.CharField(db_column='Cropname', max_length=30)),
            ],
            options={
                'db_table': 'farmer_cropname_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrantProviderT',
            fields=[
                ('grant_provider', models.OneToOneField(db_column='Grant_provider_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.financialserviceprovidert')),
                ('eligibility_criteria', models.TextField(db_column='Eligibility_criteria')),
                ('minimum_amount', models.DecimalField(db_column='Minimum_amount', decimal_places=0, max_digits=10)),
                ('maximum_amount', models.DecimalField(db_column='Maximum_amount', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'grant_provider_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceProviderT',
            fields=[
                ('insurance_provider', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.financialserviceprovidert')),
                ('premium_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'insurance_provider_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorT',
            fields=[
                ('investor', models.OneToOneField(db_column='Investor_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.financialserviceprovidert')),
            ],
            options={
                'db_table': 'investor_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrantProviderTargetT',
            fields=[
                ('grant_provider', models.OneToOneField(db_column='Grant_provider_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='krishibandhon.grantprovidert')),
                ('target_beneficiaries', models.CharField(db_column='Target_beneficiaries', max_length=40)),
            ],
            options={
                'db_table': 'grant_provider_target_t',
                'managed': False,
            },
        ),
    ]
